### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by paazmaya** [finnair/v-validation#1]
Execute tests in supported Node.js versions at Travis CI

**Comment by ssaarela** [comment]
@paazmaya Could you grant access for Travis CI?

**Comment by ssaarela** [comment]
Let's try GitHub Actions and Codecov instead.

**Comment by paazmaya** [comment]
@eostman had made already a PR for Github Actions, so that shall be used for now.

**Comment by ssaarela** [comment]
OK to close this?

**Comment by paazmaya** [comment]
Done via #8
