### ISSUE TITLE
Moment: Move from dependency to peerDependency

### ISSUE THREAD

**Issue by paazmaya** [finnair/v-validation#47]
Require/allow users to specify their own version (possibly already existing) of Moment.js.

Similar to using ESLint plugins or shared configs, they specify supported ESLint version as their peerDependency.

Any thoughts?

**Comment by ssaarela** [comment]
Sounds like the right thing to do. Would you like to make a PR for it?

**Comment by paazmaya** [comment]
@ssaarela I will do a PR during #hackoctoberfest

**Comment by paazmaya** [comment]
...empty promises
