### ISSUE TITLE
V.anyOf

### ISSUE THREAD

**Issue by ssaarela** [finnair/v-validation#50]
V already supports oneOf and allOf. It should also support anyOf: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

**Comment by karlkeskyla** [comment]
Implemented the logic and wrote the tests, so once few last quirks have been ironed out, will open a PR

**Comment by karlkeskyla** [comment]
Opened the PR:
https://github.com/finnair/v-validation/pull/52

**Comment by ssaarela** [comment]
Done in #52
