### ISSUE TITLE
Introduce alternative to moment.js

### ISSUE THREAD

**Issue by joakimsandstromfinnair** [finnair/v-validation#51]
https://github.com/finnair/v-validation/blob/277befe899b78c64453a5acc6bea1a4e49e4cc25/packages/moment/package.json#L30

Moment.js is considered to be EOL https://momentjs.com/docs/#/-project-status/ - so proposing to make something like v-validation-luxon https://moment.github.io/luxon/

**Comment by paazmaya** [comment]
I will do a PR for this, in relation to #47

**Comment by karlkeskyla** [comment]
This is done with #78.

**Comment by ssaarela** [comment]
Luxon is now supported with `@finnair/v-validation-luxon` module.
